name: Get Contributor Profile Image
on:
  push:
    branches:
    - master
    paths:
      - CONTRIBUTORS.md
jobs:
  getavatar:
    if: github.author != "github-actions"
    runs-on: ubuntu-latest
    steps:
      - name: Get the users profile avatar and commit it
        uses: actions/checkout@v2
      - run: |
          wget -O ${{ github.author }}.png https://github.com/${{ github.author }}.png?size=40
          mv ${{ github.author }}.png ./portraits/${{ github.author }}.png
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "adds avatar for ${{ github.author }}"
          git push
