name: Get Contributor Profile Image
on:
  push:
    branches:
    - master
    paths:
      - CONTRIBUTORS.md
jobs:
  getavatar:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Get the users profile avatar and commit it
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cat CONTRIBUTORS.md | grep -v img | grep -v '#' | grep -v '^$' | while read line
          do
            wget -O ${line}.png https://github.com/${line}.png?size=40
            mv ${line}.png ./portraits/${line}.png
            git add .
            git commit -m "adds avatar for ${line}"
          done
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PAT }}
