name: Get Contributor Profile Image
on:
  push:
    branches:
    - master
    paths:
      - CONTRIBUTORS.md
jobs:
  getavatar:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Get the users profile avatar and commit it
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false
      - run: |
          wget -O ${{ github.actor }}.png https://github.com/${{ github.actor }}.png?size=40
          mv ${{ github.actor }}.png ./portraits/${{ github.actor }}.png
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "adds avatar for ${{ github.actor }}"
          git push
