name: Add image to CONTRIBUTORS.md
on:
  push:
    branches:
    - master
    paths:
    - '**.png'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Add contributor profile image to CONTRIBUTORS.md
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: |
          empty=""
          ext=".png"
          for changed_file in ${{ steps.files.outputs.all }}; do
            contributor=${changed_file#portraits/}
            contributor=${contributor/$ext/$empty}
            file=$(cat CONTRIBUTORS.md)
            img="<img src='${changed_file}' title='${contributor}' style='float:left;' />"
            echo "${file/$contributor/$img}" > CONTRIBUTORS.md
          done
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updates profile in CONTRIBUTORS.md"
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PAT }}
